//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uHealthDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class facility_physician_procedures_bridge
    {
        public int ID { get; set; }
        public Nullable<int> facility_skey { get; set; }
        public Nullable<int> npi { get; set; }
        public string procedure_code { get; set; }
    
        public virtual facility_dimensions facility_dimensions { get; set; }
        public virtual procedure_base procedure_base { get; set; }
        public virtual physician_dimensions physician_dimensions { get; set; }
    }
}
