//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uHealthDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class physician_dimensions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public physician_dimensions()
        {
            this.facility_physician_procedures_bridge = new HashSet<facility_physician_procedures_bridge>();
            this.physician_insurance_bridge = new HashSet<physician_insurance_bridge>();
        }
    
        public int npi { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> specialty_skey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facility_physician_procedures_bridge> facility_physician_procedures_bridge { get; set; }
        public virtual specialty_dimensions specialty_dimensions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<physician_insurance_bridge> physician_insurance_bridge { get; set; }
    }
}
