//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uHealthDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class physician_insurance_bridge
    {
        public int ID { get; set; }
        public Nullable<int> npi { get; set; }
        public Nullable<int> insurance_skey { get; set; }
    
        public virtual insurance_dimensions insurance_dimensions { get; set; }
        public virtual physician_dimensions physician_dimensions { get; set; }
    }
}
