//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uHealthDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class procedure_facility_bridge
    {
        public int procedure_skey { get; set; }
        public string procedure_code { get; set; }
        public Nullable<int> patient_skey { get; set; }
        public Nullable<int> facility_skey { get; set; }
        public Nullable<int> npi { get; set; }
        public Nullable<System.DateTime> procedure_date { get; set; }
        public Nullable<decimal> total_cost { get; set; }
        public Nullable<int> length_of_stay { get; set; }
        public Nullable<bool> expired { get; set; }
        public Nullable<bool> major_complications { get; set; }
        public Nullable<bool> minor_complications { get; set; }
        public Nullable<bool> readmit { get; set; }
    
        public virtual facility_dimensions facility_dimensions { get; set; }
        public virtual patient_dimensions patient_dimensions { get; set; }
        public virtual procedure_code_dimensions procedure_code_dimensions { get; set; }
    }
}
