//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uHealthDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class procedure_base
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public procedure_base()
        {
            this.facility_physician_procedures_bridge = new HashSet<facility_physician_procedures_bridge>();
        }
    
        public string procedure_code { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> length_of_stay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facility_physician_procedures_bridge> facility_physician_procedures_bridge { get; set; }
        public virtual procedure_code_dimensions procedure_code_dimensions { get; set; }
    }
}
