//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uHealthDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uHealthEntities : DbContext
    {
        public uHealthEntities()
            : base("name=uHealthEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<facility_dimensions> facility_dimensions { get; set; }
        public virtual DbSet<facility_physician_procedures_bridge> facility_physician_procedures_bridge { get; set; }
        public virtual DbSet<facility_type_dimensions> facility_type_dimensions { get; set; }
        public virtual DbSet<insurance_dimensions> insurance_dimensions { get; set; }
        public virtual DbSet<patient_dimensions> patient_dimensions { get; set; }
        public virtual DbSet<physician_dimensions> physician_dimensions { get; set; }
        public virtual DbSet<physician_insurance_bridge> physician_insurance_bridge { get; set; }
        public virtual DbSet<procedure_base> procedure_base { get; set; }
        public virtual DbSet<procedure_code_dimensions> procedure_code_dimensions { get; set; }
        public virtual DbSet<procedure_facility_bridge> procedure_facility_bridge { get; set; }
        public virtual DbSet<specialty_dimensions> specialty_dimensions { get; set; }
    }
}
